installer:
  release: "v0.3.27"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:1d34783e-51-8382"
  devtron:
    image: "quay.io/devtron/hyperion:0e102b62-282-8340"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:1be465ec-318-7966"
  postgres:
    image: "quay.io/devtron/postgres:11.3.0-debian-9-r28"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "module_mvp"
        GIT_HASH: "0e102b62ecb99c29e6ed0e528bbfd93f5e36253f"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "a5f55594f7e1c41fc77e5915b9e6f6df537da4da"
