installer:
  release: "v0.4.0"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:5a7371a0-51-8268"
  devtron:
    image: "quay.io/devtron/hyperion:53733868-282-8315"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:1be465ec-318-7966"
  postgres:
    image: "quay.io/devtron/postgres:11.3.0-debian-9-r28"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "module_mvp"
        GIT_HASH: "537338688633339e091b08041b3692744c5cc789"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "a5f55594f7e1c41fc77e5915b9e6f6df537da4da"
